#!/bin/sh
target_path=${1}
cd ${target_path}
# squashfs pseudo file list (-pf)
# generated by ./prepare-squashfs.sh
#	/home/weiss/ramdisk/demo-ws
#	config_overlay/hammerhead/rootdir_a0/
#	config_overlay/hammerhead/squashfs/prepare-pf#	config_overlay/hammerhead/squashfs/prepare.sh
# at Tue May 31 10:27:03 CEST 2016

echo Generating symlinks in ${target_path}
echo -e tt mkdir storage/emulated
mkdir -p -m 755 storage/emulated
echo -e tt mkdir persist
mkdir -p -m 771 persist
echo -e tt mkdir firmware
mkdir -p -m 771 firmware
echo -e tt mkdir acct
mkdir -p -m 755 acct
echo -e tt mkdir acct/uid
mkdir -p -m 755 acct/uid
echo -e tt mkdir system
mkdir -p -m 755 system
echo -e tt mkdir data
mkdir -p -m 755 data
echo -e tt mkdir cache
mkdir -p -m 755 cache
echo -e tt mkdir config
mkdir -p -m 755 config
echo -e tt mkdir mnt
mkdir -p -m 755 mnt
echo -e tt mkdir storage
mkdir -p -m 755 storage

# for dynamic properties at startup
echo -e tt mkdir factory
mkdir -p -m 755 factory

# squashfs symlink script 
# generated by ./prepare-squashfs.sh
#	/home/weiss/ramdisk/demo-ws
#	config_overlay/hammerhead/rootdir_a0/
#	config_overlay/hammerhead/squashfs/prepare-pf#	config_overlay/hammerhead/squashfs/prepare.sh
# at Tue May 31 10:27:03 CEST 2016

echo Generating symlinks in ${target_path}
echo -e tt symlink /storage/emulated/legacy sdcard
mkdir -p -m 755 $(dirname sdcard)
ln -sf /storage/emulated/legacy sdcard
echo -e tt symlink /storage/emulated/legacy storage/sdcard0
mkdir -p -m 755 $(dirname storage/sdcard0)
ln -sf /storage/emulated/legacy storage/sdcard0
echo -e tt symlink /mnt/shell/emulated/0 storage/emulated/legacy
mkdir -p -m 755 $(dirname storage/emulated/legacy)
ln -sf /mnt/shell/emulated/0 storage/emulated/legacy
echo -e tt symlink /sdcard storage/sdcard0
mkdir -p -m 755 $(dirname storage/sdcard0)
ln -sf /sdcard storage/sdcard0
echo -e tt symlink /system/etc etc
mkdir -p -m 755 $(dirname etc)
ln -sf /system/etc etc
echo -e tt symlink /sys/kernel/debug d
mkdir -p -m 755 $(dirname d)
ln -sf /sys/kernel/debug d
echo -e tt symlink /system/vendor vendor
mkdir -p -m 755 $(dirname vendor)
ln -sf /system/vendor vendor
echo -e tt symlink /storage/self/primary sdcard
mkdir -p -m 755 $(dirname sdcard)
ln -sf /storage/self/primary sdcard
